# Simple workflow for deploying static content to GitHub Pages
# Zvika based on https://vitejs.dev/guide/static-deploy#github-pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json' # bebacuse my 'package-lock.json' isn't at root
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          VITE_DB_API_URL: ${{ secrets.VITE_DB_API_URL }}
          VITE_DB_API_KEY: ${{ secrets.VITE_DB_API_KEY }}
          VITE_DB_ENDPOINT_URL: ${{ secrets.VITE_DB_ENDPOINT_URL }}
          VITE_CHECK: ${{ secrets.VITE_CHECK }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './frontend/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
